tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/set_tf_alias
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli
      source ./bin/set_tf_alias
  - name: Install eksctl
    command: |
      ARCH=amd64
      PLATFORM=$(uname -s)_$ARCH

      curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

      # (Optional) Verify checksum
      curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

      tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

      sudo mv /tmp/eksctl /usr/local/bin/eksctl
      sudo chmod +x /usr/local/bin/eksctl
      sudo apt-get install -y eksctl
  - name: Install kubectl
    before: |
      source ./bin/install_kubectl
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - donjayamanne.githistory
    - phil294.git-log--graph
    - mhutchie.git-graph
    - phil294.git-log--graph
